export enum ActivityEntityType {
  User = 'User',
  Role = 'Role',
  Permission = 'Permission',
  BrickType = 'BrickType',
  Position = 'Position',
  ProductionPlan = 'ProductionPlan',
  StageAssignment = 'StageAssignment',
  DailyStageProduction = 'DailyStageProduction',
  QualityRecord = 'QualityRecord',
  MeasurementCache = 'MeasurementCache',
  Workshop = 'Workshop',
  ProductionLine = 'ProductionLine',
  Device = 'Device',
  DeviceCluster = 'DeviceCluster',
  ProductionMetric = 'ProductionMetric',
  QuotaTarget = 'QuotaTarget',
  Setting = 'Setting',
  Other = 'Other',
  Attachment = 'Attachment',
  ApiToken = 'ApiToken',
  MeasurementType = 'MeasurementType',
  SalaryPeriod = 'SalaryPeriod',
}

export enum ActivityStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum ActivitySeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SECURITY = 'SECURITY', // hành động nhạy cảm
}

export enum ActivitySource {
  WEB_ADMIN = 'WEB_ADMIN',
  WEB_APP = 'WEB_APP',
  API = 'API',
  IOT_SYNC = 'IOT_SYNC',
  JOB = 'JOB', // cron / background job
  SYSTEM = 'SYSTEM', // hành động hệ thống tự làm
}


export type ActivityAction =
  // AUTH
  | 'LOGIN_SUCCESS'
  | 'LOGIN_FAILED'
  | 'LOGOUT'
  | 'REFRESH_TOKEN'
  | 'CHANGE_PASSWORD'
  | 'RESET_PASSWORD_REQUEST'
  | 'RESET_PASSWORD_CONFIRM'
  | 'ENABLE_2FA'
  | 'DISABLE_2FA'
  | 'LOCK_ACCOUNT'
  | 'UNLOCK_ACCOUNT'

  // USER & ROLE / PERMISSION
  | 'CREATE_USER'
  | 'UPDATE_USER_PROFILE'
  | 'UPDATE_USER_STATUS'
  | 'UPDATE_USER_ROLE'
  | 'ASSIGN_ROLE'
  | 'REVOKE_ROLE'
  | 'CREATE_ROLE'
  | 'UPDATE_ROLE'
  | 'DELETE_ROLE'
  | 'CREATE_PERMISSION'
  | 'UPDATE_PERMISSION'
  | 'DELETE_PERMISSION'
  | 'VIEW_PROFILE'

  // MASTER DATA: BRICK, WORKSHOP, LINE, DEVICE...
  | 'CREATE_BRICK_TYPE'
  | 'UPDATE_BRICK_TYPE'
  | 'DISABLE_BRICK_TYPE'
  | 'ENABLE_BRICK_TYPE'
  | 'DELETE_BRICK_TYPE'
  | 'CREATE_WORKSHOP'
  | 'UPDATE_WORKSHOP'
  | 'DISABLE_WORKSHOP'
  | 'ENABLE_WORKSHOP'
  | 'DELETE_WORKSHOP'
  | 'CREATE_PRODUCTION_LINE'
  | 'UPDATE_PRODUCTION_LINE'
  | 'DISABLE_PRODUCTION_LINE'
  | 'ENABLE_PRODUCTION_LINE'
  | 'DELETE_PRODUCTION_LINE'
  | 'CREATE_POSITION'
  | 'UPDATE_POSITION'
  | 'UPDATE_POSITION_INDEX'
  | 'DELETE_POSITION'
  | 'CREATE_MEASUREMENT_TYPE'
  | 'UPDATE_MEASUREMENT_TYPE'
  | 'DISABLE_MEASUREMENT_TYPE'
  | 'ENABLE_MEASUREMENT_TYPE'
  | 'DELETE_MEASUREMENT_TYPE'
  | 'CREATE_DEVICE'
  | 'UPDATE_DEVICE'
  | 'DISABLE_DEVICE'
  | 'ENABLE_DEVICE'
  | 'DELETE_DEVICE'
  | 'CREATE_DEVICE_CLUSTER'
  | 'UPDATE_DEVICE_CLUSTER'
  | 'DISABLE_DEVICE_CLUSTER'
  | 'ENABLE_DEVICE_CLUSTER'
  | 'DELETE_DEVICE_CLUSTER'

  // PRODUCTION PLAN
  | 'CREATE_PRODUCTION_PLAN'
  | 'UPDATE_PRODUCTION_PLAN'
  | 'APPROVE_PRODUCTION_PLAN'
  | 'REJECT_PRODUCTION_PLAN'
  | 'CANCEL_PRODUCTION_PLAN'
  | 'CLOSE_PRODUCTION_PLAN'
  | 'REOPEN_PRODUCTION_PLAN'
  | 'COPY_PRODUCTION_PLAN'

  // STAGE ASSIGNMENT
  | 'START_STAGE_ASSIGNMENT'
  | 'STOP_STAGE_ASSIGNMENT'
  | 'UPDATE_STAGE_ASSIGNMENT'
  | 'SPLIT_STAGE_ASSIGNMENT'
  | 'MERGE_STAGE_ASSIGNMENT'

  // DAILY PRODUCTION
  | 'SYNC_DAILY_PRODUCTION'
  | 'IMPORT_DAILY_PRODUCTION'
  | 'ADJUST_DAILY_PRODUCTION'
  | 'DELETE_DAILY_PRODUCTION'

  // QUALITY
  | 'INPUT_QUALITY_RECORD'
  | 'UPDATE_QUALITY_RECORD'
  | 'DELETE_QUALITY_RECORD'
  | 'IMPORT_QUALITY_RECORD'

  // IOT & MEASUREMENT
  | 'SYNC_TELEMETRY_BATCH'
  | 'SYNC_MEASUREMENT_CACHE'
  | 'PURGE_MEASUREMENT_CACHE'
  | 'DEVICE_TIMEOUT'
  | 'DEVICE_RECOVERED'
  | 'UPDATE_DEVICE_CONFIG'
  | 'UPDATE_CLUSTER_CONFIG'
  | 'TEST_DEVICE_CONNECTION'
  | 'TEST_MQTT_PUBLISH'

  // SALARY & KPI
  | 'RUN_SALARY_CALCULATION'
  | 'RERUN_SALARY_CALCULATION'
  | 'APPROVE_SALARY'
  | 'REJECT_SALARY'
  | 'ADJUST_SALARY_ITEM'
  | 'LOCK_SALARY_PERIOD'
  | 'UNLOCK_SALARY_PERIOD'
  | 'RUN_KPI_CALCULATION'

  // REPORT & EXPORT
  | 'EXPORT_PRODUCTION_REPORT'
  | 'EXPORT_QUALITY_REPORT'
  | 'EXPORT_SALARY_REPORT'
  | 'EXPORT_DEVICE_LOG'
  | 'EXPORT_PLAN_LIST'
  | 'GENERATE_DASHBOARD_SNAPSHOT'

  // SETTINGS & SYSTEM
  | 'UPDATE_SYSTEM_SETTING'
  | 'RESET_SYSTEM_SETTING'
  | 'BACKUP_DATABASE'
  | 'RESTORE_DATABASE'
  | 'RUN_MIGRATION'
  | 'ROLLBACK_MIGRATION'
  | 'START_BACKGROUND_JOB'
  | 'STOP_BACKGROUND_JOB'

  // QUOTA TARGETS
  | 'CREATE_QUOTA_TARGET'
  | 'UPDATE_QUOTA_TARGET'
  | 'DELETE_QUOTA_TARGET'

  // PRODUCTION METRICS
  | 'CREATE_PRODUCTION_METRIC'
  | 'UPDATE_PRODUCTION_METRIC'
  | 'DELETE_PRODUCTION_METRIC'

  // TOKEN / API KEY
  | 'GENERATE_API_TOKEN'
  | 'REVOKE_API_TOKEN'

  // FILE / ATTACHMENT
  | 'UPLOAD_ATTACHMENT'
  | 'DELETE_ATTACHMENT'

  // MQTT / DEVICE COMMANDS
  | 'TEST_MQTT_PUBLISH_ONCE'
  | 'TEST_MQTT_PUBLISH_CONTINUOUS'
  | 'RESET_DEVICE_COUNTER'
  | 'RESET_LINE_COUNTER'
  | 'RESET_CLUSTER_COUNTER'
  | 'EMERGENCY_STOP_LINE'
  | 'SET_DEVICE_COUNTER'
  | 'CONFIG_DEVICE'
  | 'CONFIG_LINE'

  // OTHER
  | 'MANUAL_DATA_FIX'
  | 'OTHER_ACTION';
